/*
 * File: app/controller/Accelerometer.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IrdaEval.controller.Accelerometer', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            accView: '#accView',
            xValue: '#accX'
        },

        control: {
            "#accView": {
                activate: 'onAccViewActivate'
            }
        }
    },

    onAccViewActivate: function(container, newActiveItem, oldActiveItem, options) {
        //wait for PhoneGap to load
        // document.addEventListener("deviceready", loaded, false);
        console.log('AccView activated.');

    },

    onSuccess: function(acceleration) {
        var me = this;
        var x = me.getXValue;
        x = acceleration.x;

    },

    startWatch: function() {
        // Update acceleration every 3 seconds
        var options = { frequency: 3000 };

        watchID = navigator.accelerometer.watchAcceleration(onSuccess, onError, options);

    },

    stopWatch: function() {
        if (watchID) {
            navigator.accelerometer.clearWatch(watchID);
            watchID = null;
        }

    },

    loaded: function() {
        startWatch();

    },

    onError: function() {
        alert('onError!');

    }

});