/*
 * File: app/controller/MainNavController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IrdaEval.controller.MainNavController', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            nav: '#mainNav',
            evalList: '#evalList'
        },

        control: {
            "#evalList": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, options) {
        var me = this,
            evalmodule,
            nextView;

        if (record) {


            console.log('got here');
            var nav = me.getNav();
            evalmodule = record.get('name');
            console.log('Record name = %s', evalmodule);

            if ( evalmodule == 'Buttons' ) {
                nextView = Ext.create('IrdaEval.view.EvaluateButtons', {
                    title: 'Evaluate Buttons'
                });
                console.log('Button eval selected, ButtonsView = %s', nextView);
            } else if (evalmodule == 'Picker'){
                nextView = Ext.create('IrdaEval.view.PickerContainer', {
                    title: 'Evaluate Picker'
                });
                console.log('Picker eval selected, PickerView = %s', nextView);
            } else if (evalmodule == 'Images'){
                nextView = Ext.create('IrdaEval.view.ImageContainer', {
                    title: 'Evaluate Images'
                });
                console.log('Image eval selected, ImageView = %s', nextView);
            } else if (evalmodule == 'File IO'){
                nextView = Ext.create('IrdaEval.view.EvaluateFile', {
                    title: 'Evaluate File IO'
                });
                console.log('File eval selected, view = %s', nextView);
            } else if (evalmodule == 'Camera'){
                nextView = Ext.create('IrdaEval.view.CameraView', {
                    title: 'Evaluate Camera'
                });
                console.log('Camera eval selected, view = %s', nextView);
            } else if (evalmodule == 'Sliders'){
                nextView = Ext.create('IrdaEval.view.SlidersView', {
                    title: 'Evaluate Sliders'
                });
                console.log('Slider eval selected, view = %s', nextView);
            } else if (evalmodule == 'Accelerometer'){
                nextView = Ext.create('IrdaEval.view.AccelerometerView', {
                    title: 'Evaluate Accelerometer'
                });
                console.log('Accelerometer eval selected, view = %s', nextView);
            }
            nav.push(nextView);
        }
    },

    init: function(application) {
        var me = this;

    }

});