/*
 * File: app/view/EvaluateButtons.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IrdaEval.view.EvaluateButtons', {
    extend: 'Ext.Container',

    config: {
        layout: {
            pack: 'center',
            type: 'vbox'
        },
        items: [
            {
                xtype: 'spacer',
                docked: 'left',
                width: 50
            },
            {
                xtype: 'spacer',
                docked: 'right',
                width: 50
            },
            {
                xtype: 'button',
                docked: 'top',
                margin: 10,
                text: 'MyButton3'
            },
            {
                xtype: 'container',
                height: 78,
                width: 241,
                items: [
                    {
                        xtype: 'button',
                        text: 'Standard Button'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'MyFieldSet',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Field'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Field'
                    },
                    {
                        xtype: 'button',
                        text: 'MyButton4'
                    }
                ]
            }
        ]
    }

});