/*
 * File: app/view/PickerContainer.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('IrdaEval.view.PickerContainer', {
    extend: 'Ext.Container',

    config: {
        items: [
            {
                xtype: 'picker',
                ui: '',
                useTitles: true,
                slots: [
                    {
                        xtype: 'pickerslot',
                        align: 'center',
                        data: [
                            {
                                text: 'Tom',
                                value: 1
                            },
                            {
                                text: 'Brian',
                                value: 2
                            },
                            {
                                text: 'Sara',
                                value: 3
                            },
                            {
                                text: 'Dale',
                                value: 4
                            },
                            {
                                text: 'J',
                                value: 5
                            },
                            {
                                text: 'Greg',
                                value: 6
                            }
                        ],
                        name: 'MyPickerSlot',
                        title: 'IRDA Employee'
                    }
                ]
            }
        ]
    }

});